### ISSUE TITLE
Can not compile with ADL support (can not understand problem origin)

### ISSUE THREAD

**Issue by rumatoest** [genesismining/sgminer-gm#41]
I'm not able to compile with ADL support on ubuntu 16.04 and gcc 5.
It is really confusing but I can not understand origin of this issuie because I see function definition in adl.h and it included to driver-opencl.c
So it looks like it must work but it does not :(
```
sgminer-driver-opencl.o: In function `opencl_detect':
driver-opencl.c:(.text+0xd8d): undefined reference to `init_adl'
collect2: error: ld returned 1 exit status
Makefile:854: recipe for target 'sgminer' failed
make[2]: *** [sgminer] Error 1
make[2]: Leaving directory '/home/miner/miners/sgminer-gm'
Makefile:1721: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/miner/miners/sgminer-gm'
Makefile:663: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jramos** [comment]
Try configuring like this:

```
CFLAGS="-O2 -std=gnu99 -I/opt/AMDAPPSDK-3.0/include" LDFLAGS="-rdynamic -L/opt/amdgpu-pro/lib/x86_64-linux-gnu" ./configure
```

Also, make sure you copy the header files from the ADL download to the ADL_SDK folder. You should have these files:

```
$ ls -1 ADL_SDK/
adl_defines.h
adl_sdk.h
adl_structures.h
```

**Comment by DominiLux** [comment]
Here are some very detailed instructions
[https://github.com/genesismining/sgminer-gm/wiki/Compile-sgminer-5.5.5-in-Ubuntu-16.04.1-LTS](url)

**Comment by rumatoest** [comment]
Thanks it is working solution. So please update Readme or just add link to wiki from Readme

**Comment by jduncan8142** [comment]
This help but now I'm this error:

`Makefile:1076: recipe for target 'sgminer-adl.o' failed
make[1]: *** [sgminer-adl.o] Error 1
make[1]: Leaving directory '/home/miner/sgminer-gm-x16r'
Makefile:1721: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
`
